version: "3"

services:
  dockerize-nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    image: dockerize-nextjs-image
    container_name: dockerize-nextjs-container
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
