version: "3"

services:
  docker-compose-with-next:
    build:
      context: .
      dockerfile: ./Dockerfile4
    image: docker-compose-with-next
    container_name: docker-compose-with-next-container
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
